---
# vars file for docker
docker_compose_version: "1.27.4"
dependencies:
- apt-transport-https
- ca-certificates
- curl
- software-properties-common
- gnupg-agent
packages:
- docker-ce
- docker-ce-cli
- containerd.io

