---
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install zsh
  apt:
    package: zsh
    state: present

- name: Change user shell to zsh
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
