---
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install tmux software package
  become: true
  package:
    name: tmux
    state: present

- name: Update tmux configuration file
  ansible.builtin.template:
    src: ./files/.tmux.conf
    dest: ~/.tmux.conf
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"
  notify: Configure tmux source file
