---
- name: Update apt-get repo and cache
  become: true
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install vim
  become: true
  apt:
    package: vim
    state: present

- name: Configure vim
  copy:
    src: files/.vimrc
    dest: $HOME/.vimrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
